version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  java-app:
    build:
      context: .
    container_name: portafolio-java
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  face-tracker:
    build:
      context: ./apps/face-tracker
    container_name: face-tracker
    restart: unless-stopped
    environment:
      - DISPLAY=:0

  web-scraper:
    build:
      context: ./apps/web-scraper
    container_name: web-scraper
    volumes:
      - ./apps/web-scraper:/app
    command: scrapy crawl ejemplo -o resultados.json


volumes:
  pgdata:
